// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Link struct {
	ID       int64
	Name     string
	Url      string
	Icon     sql.NullString
	Category sql.NullString
	Colour   sql.NullString
	Hits     int64
}
