// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const createLink = `-- name: CreateLink :one
INSERT INTO
  links (name, url, icon, category, colour, hits)
VALUES
  (?, ?, ?, ?, ?, ?) RETURNING id, name, url, icon, category, colour, hits
`

type CreateLinkParams struct {
	Name     string
	Url      string
	Icon     sql.NullString
	Category sql.NullString
	Colour   sql.NullString
	Hits     int64
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Category,
		arg.Colour,
		arg.Hits,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Category,
		&i.Colour,
		&i.Hits,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE
  id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const listLinks = `-- name: ListLinks :many
SELECT
  id, name, url, icon, category, colour, hits
FROM
  links
ORDER BY
  hits
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Category,
			&i.Colour,
			&i.Hits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryLink = `-- name: QueryLink :one
SELECT id, name, url, icon, category, colour, hits FROM links WHERE id = ?
`

func (q *Queries) QueryLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, queryLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Category,
		&i.Colour,
		&i.Hits,
	)
	return i, err
}

const recordHit = `-- name: RecordHit :exec
UPDATE links
SET
  hits = hits + 1
WHERE
  id = ?
`

func (q *Queries) RecordHit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, recordHit, id)
	return err
}

const searchLinks = `-- name: SearchLinks :many
SELECT
  id, name, url, icon, category, colour, hits
FROM
  links
WHERE
  LOWER(name) LIKE LOWER('%' || ?1 || '%')
  OR LOWER(url) LIKE LOWER('%' || ?1 || '%')
ORDER BY
  hits DESC
`

func (q *Queries) SearchLinks(ctx context.Context, query sql.NullString) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, searchLinks, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Category,
			&i.Colour,
			&i.Hits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :exec
UPDATE links
SET
  name = ?1,
  url = ?2,
  icon = COALESCE(NULLIF(CAST(?3 AS TEXT), ''), icon),
  category = ?4,
  colour = ?5
WHERE
  id = ?6
`

type UpdateLinkParams struct {
	Name     string
	Url      string
	Icon     string
	Category sql.NullString
	Colour   sql.NullString
	ID       int64
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateLink,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Category,
		arg.Colour,
		arg.ID,
	)
	return err
}
